### ISSUE TITLE
Race conditions with snapshot

### ISSUE THREAD

**Issue by junkblocker** [malthe/macfsevents#13]
Assuming we have a somewhat deep directory structure at `dir_a` which has some directory `dir_y` under it. It is very easy to generate a `KeyError` by doing the following

```
% mv dir_a dir_new ; rm -rf dir_new/some/levels/here/dir_y

Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/Library/Python/2.7/site-packages/fsevents.py", line 44, in run
    _fsevents.loop(self)
  File "/Library/Python/2.7/site-packages/fsevents.py", line 128, in __call__
    snapshot = self.snapshots[path]
KeyError: '/Users/xxxx/tmp/dir_new/some/levels/here/dir_y'
```

**Comment by stephenptem** [comment]
Same here. I can replicate with consistency by doing `rm -rf node_modules` and `npm install` on a large node project
