### ISSUE TITLE
AttributeError: 'dict_keys' object has no attribute 'sort'

### ISSUE THREAD

**Issue by jacebrowning** [malthe/macfsevents#31]
I am using `MacFSEvents` with [sniffer](https://github.com/jeffh/sniffer). It seems that the recent `0.5` release caused a regression in Python 3.5:

```
env/bin/sniffer
Traceback (most recent call last):
  File "env/bin/sniffer", line 7, in <module>
    from sniffer import main
  File "<...>/env/lib/python3.5/site-packages/sniffer/__init__.py", line 26, in <module>
    from .scanner import Scanner
  File "<...>/env/lib/python3.5/site-packages/sniffer/scanner/__init__.py", line 34, in <module>
    _import('fsevents_scanner', 'FSEventsScanner')    # osx
  File "<...>/env/lib/python3.5/site-packages/sniffer/scanner/__init__.py", line 28, in _import
    mod = __import__(str(module), globals(), locals(), [cls], 1)
  File "<...>/env/lib/python3.5/site-packages/sniffer/scanner/fsevents_scanner.py", line 9, in <module>
    import fsevents
  File "<...>/env/lib/python3.5/site-packages/fsevents.py", line 47, in <module>
    class Mask(int):
  File "<...>/env/lib/python3.5/site-packages/fsevents.py", line 72, in Mask
    svals.sort()
AttributeError: 'dict_keys' object has no attribute 'sort'
make: *** [watch] Error 1
```

If I specifically install the previous release (`$ pip install MacFSEvents==0.4`), I do not see this issue.

**Comment by malthe** [comment]
This should be fixed now – can you try release 0.6?

**Comment by jacebrowning** [comment]
I get a different error with `0.6`:

```
Traceback (most recent call last):
  File "env/bin/sniffer", line 7, in <module>
    from sniffer import main
  File "<...>/env/lib/python3.4/site-packages/sniffer/__init__.py", line 26, in <module>
    from .scanner import Scanner
  File "<...>/env/lib/python3.4/site-packages/sniffer/scanner/__init__.py", line 34, in <module>
    _import('fsevents_scanner', 'FSEventsScanner')    # osx
  File "<...>/env/lib/python3.4/site-packages/sniffer/scanner/__init__.py", line 28, in _import
    mod = __import__(str(module), globals(), locals(), [cls], 1)
  File "<...>/env/lib/python3.4/site-packages/sniffer/scanner/fsevents_scanner.py", line 9, in <module>
    import fsevents
  File "<...>/env/lib/python3.4/site-packages/fsevents.py", line 47, in <module>
    class Mask(int):
TypeError: nonempty __slots__ not supported for subtype of 'int'
```

**Comment by malthe** [comment]
Can you try 91666d5 and see if it fixes things for you or if there are any more issues? I don't have a Mac so I can't really test things out very easily :-(

**Comment by jacebrowning** [comment]
Travis CI offers continuous integration on OSX for free. Would you accept a pull request that turns that on for this project?

**Comment by malthe** [comment]
Definitely, yes. That would be great. I'm struggling to properly maintain this project since I'm not actively using Mac OS X these days for development :-)

**Comment by jacebrowning** [comment]
From my testing, it seems that completely removing `__slots__` is required: https://github.com/malthe/macfsevents/pull/33

With 91666d5, I got the same exception as `0.6`.
