### ISSUE TITLE
import failure on python 3.5

### ISSUE THREAD

**Issue by DanLipsitt** [malthe/macfsevents#35]
With MacFSEvents 0.6 from PyPi:

```
$ python3.5 -c 'import fsevents'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/dan/.virtualenvs/pod/lib/python3.5/site-packages/fsevents.py", line 47, in <module>
    class Mask(int):
TypeError: nonempty __slots__ not supported for subtype of 'int'
```

**Comment by malthe** [comment]
Could you try 0.7 (just uploaded now) – ?

**Comment by DanLipsitt** [comment]
That works, thanks! Unit tests pass.
