### ISSUE TITLE
KeyError crashes program

### ISSUE THREAD

**Issue by seaside98** [malthe/macfsevents#36]
Here is the error:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/site-packages/MacFSEvents-0.8.dev0-py2.7-macosx-10.9-x86_64.egg/fsevents.py", line 133, in run
    loop(self)
  File "/usr/local/lib/python2.7/site-packages/MacFSEvents-0.8.dev0-py2.7-macosx-10.9-x86_64.egg/fsevents.py", line 244, in __call__
    snapshot = self.snapshots[path]
KeyError: '/Volumes/deliveries/test.com/fcDisk/Shared_Files/dhemme'
```
Any ideas? I've seen this several times.

**Comment by seaside98** [comment]
For anyone who comes across this in the future, your watched paths MUST match the case (as in, case sensitive) of the actual path.

**Comment by stephenptem** [comment]
Same as #13 
Also having this issue
