### ISSUE TITLE
Installing 0.8 fails due to missing CHANGES.rst in the source distribution

### ISSUE THREAD

**Issue by Kwpolska** [malthe/macfsevents#42]
An attempt to install `macfsevents==0.8` fails due to a missing file error. It looks like `CHANGES.rst` is not included in the source distribution (it must be mentioned in `MANIFEST.in`).

```pytb
  Downloading MacFSEvents-0.8.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/pip-build-amqza803/macfsevents/setup.py", line 22, in <module>
        long_description = "\n\n".join((read('README.rst'), read('CHANGES.rst'))),
      File "/private/var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/pip-build-amqza803/macfsevents/setup.py", line 8, in read
        with open(os.path.join(os.path.dirname(__file__), fname)) as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/pip-build-amqza803/macfsevents/CHANGES.rst'
```

**Comment by malthe** [comment]
Please try release 0.8.1 – should be fixed.

**Comment by Kwpolska** [comment]
It works. Thanks for fixing this so quickly.
